on:
  pull_request

jobs:
  start:
    runs-on: windows-latest
    name: pull_request-example_without_proxy.js
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          architecture: 'x64'
      - run: npm install
      - run: node example_without_proxy.js